[package]
name = "canna_scrape_web"
version = "0.1.0"
authors = ["Weston <wez470@gmail.com>"]

[dependencies]
select = "0.4.2"
reqwest = "0.8.3"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"